/* Zera HSC Sequence Registry™ v1.0
 * Généalogie constitutive : PROBLÈME → LOI → HOQ → SÉQUENCE → CODE → YEHI.
 */
(function(root){
  'use strict';
  const CONTRACT=Object.freeze({
    sequence_id:'SEQ-ZERA-EARTHBOUND-001',version:'1.0.0',status:'AUTHORIZED',
    problem_id:'PROBLEM-ZERA-002',
    problem:'Une projection GPS globale peut produire une migration de plusieurs Zera ou masquer un déplacement terrestre réel vers une cellule voisine.',
    law_id:'LAW-ZERA-EARTHBOUND-001',
    law:'Une Présence terrestre ne manifeste que la cellule courante ou une cellule immédiatement voisine déjà constituée dans le potentiel Qedimah de la rue.',
    hoq_id:'HOQ-ZERA-LOCAL-SEQUENCE-001',
    states:['GPS_OBSERVED','ACQUISITION_AUTHORIZED','STREET_CONFIRMED','P0_OPENED','LOCAL_WINDOW_OPENED','WITNESSES_EVALUATED','POSITION_MAINTAINED','ADJACENT_MANIFESTED','NON_ADJACENT_BANNED'],
    preconditions:['FOUR_GOVERNED_SAMPLES_OR_MANUAL_INPUT','STREET_REFERENCE_AVAILABLE','P0_STREET_ZERA_TESSELLATION_AVAILABLE','PREVIOUS_GOVERNED_ZERA_AVAILABLE_AFTER_P1'],
    transitions:[
      'GPS_OBSERVED→ACQUISITION_AUTHORIZED','ACQUISITION_AUTHORIZED→STREET_CONFIRMED','STREET_CONFIRMED→P0_OPENED','P0_OPENED→LOCAL_WINDOW_OPENED','LOCAL_WINDOW_OPENED→WITNESSES_EVALUATED','WITNESSES_EVALUATED→POSITION_MAINTAINED','WITNESSES_EVALUATED→ADJACENT_MANIFESTED','LOCAL_WINDOW_OPENED→NON_ADJACENT_BANNED'
    ],
    forbidden_transitions:['GPS_OBSERVED→ADJACENT_MANIFESTED','GPS_OBSERVED→NON_ADJACENT_POSITION','Zn→Zn±2_OR_MORE','OMEH_ALONE→ADJACENT_MANIFESTED','GLOBAL_PROJECTION_SCORE→GOVERNED_POSITION'],
    modules:{
      'MOD-247':'LOCAL_ZERA_WINDOW_AND_TWO_WITNESS_CONSTRAINT_STRUCTURED',
      'MOD-086':'LINEAGE_AND_CONTRACT_REGISTERED',
      'MOD-025':'AUTHORIZATION_TOKEN_ISSUED',
      'MOD-207a':'ONLY_Zn_MINUS_1_Zn_Zn_PLUS_1_CAN_BE_GOVERNED',
      'MOD-031':'EARTHBOUND_LOCAL_CONTINUITY_EXECUTION',
      'MOD-207b':'MANIFEST_ADJACENT_OR_MAINTAIN_AND_REPORT_DIVERGENCE'
    },
    functionality_expected:'EXCLUDE_NON_ADJACENT_CELLS_BEFORE_SCORING_AND_REQUIRE_TWO_INDEPENDENT_WITNESSES_FOR_A_ONE_ZERA_MOVE',
    execution_id:'EXEC-ZERA-EARTHBOUND-001',
    authorization_token:'YEHI-ZERA-EARTHBOUND-001-20260822'
  });
  const PATH_CONTRACT=Object.freeze({
    sequence_id:'SEQUENCE-ZERA-PATH-001',version:'1.0.0',status:'AUTHORIZED',
    problem_id:'PROBLEM-ZERA-003',
    problem:'Une observation distante peut correspondre soit à une dérive GPS, soit à un mouvement terrestre multi-cellule que le filtre anti-saut ramène actuellement à zéro.',
    law_id:'LAW-ZERA-PATH-001',
    law:'Tout mouvement multi-cellule manifesté doit être un chemin ordonné de Zera adjacentes préexistantes, dont la traversée est soutenue par des familles de preuves indépendantes.',
    hoq_id:'HOQ-ZERA-PATH-001',
    states:['GOVERNED_AT_ORIGIN','DESTINATION_CANDIDATE_IDENTIFIED','NON_ADJACENT_GAP_DETECTED','QEDEM_PATH_SEARCH','PATH_NOT_FOUND','PATH_CANDIDATE','PATH_SUPPORTED','PATH_AMBIGUOUS','PATH_VALIDATED','PATH_REJECTED','HOLD_LAST_GOVERNED_POSITION','MANIFEST_TRANSITIONS','GOVERNED_AT_DESTINATION'],
    preconditions:['LAST_GOVERNED_ZERA_AVAILABLE','QEDIMAH_STREET_GRAPH_AVAILABLE','DESTINATION_REMAINS_CANDIDATE','EVIDENCE_SOURCE_PROVENANCE_AVAILABLE'],
    transitions:['GOVERNED_AT_ORIGIN→DESTINATION_CANDIDATE_IDENTIFIED','DESTINATION_CANDIDATE_IDENTIFIED→NON_ADJACENT_GAP_DETECTED','NON_ADJACENT_GAP_DETECTED→QEDEM_PATH_SEARCH','QEDEM_PATH_SEARCH→PATH_CANDIDATE','QEDEM_PATH_SEARCH→PATH_NOT_FOUND','PATH_CANDIDATE→PATH_SUPPORTED','PATH_SUPPORTED→PATH_VALIDATED','PATH_CANDIDATE→HOLD_LAST_GOVERNED_POSITION','PATH_VALIDATED→MANIFEST_TRANSITIONS','MANIFEST_TRANSITIONS→GOVERNED_AT_DESTINATION'],
    forbidden_transitions:['Zn→Zn±k_WITHOUT_INTERMEDIATE_CELLS','PATH_CANDIDATE→GOVERNED_AT_DESTINATION','OMEH_ALONE→PATH_VALIDATED','GPS_DISTANCE_DIVIDED_BY_ZERA→GOVERNED_MOVEMENT','REJECTED_DESTINATION→NEW_ORIGIN','UNVALIDATED_SUFFIX→PARTIAL_MANIFESTATION'],
    modules:{
      'MOD-247':'PATH_OBJECTS_STATES_WITNESSES_AND_MANIFESTATION_CONSTRAINTS_STRUCTURED',
      'MOD-086':'PROBLEM_ZERA_003_TO_LAW_TO_HOQ_TO_SEQUENCE_REGISTERED',
      'MOD-025':'AUTHORIZATION_TOKEN_ISSUED',
      'MOD-207a':'RECONSTRUCT_PREEXISTING_ADJACENT_PATH_WITHOUT_PREMATURE_MANIFESTATION',
      'MOD-031':'ZERA_GOVERNED_PATH_RESOLVER_EXECUTION',
      'MOD-207b':'MANIFEST_VALIDATED_PATH_OR_HOLD_LAST_GOVERNED_ZERA'
    },
    functionality_expected:'CONVERT_A_NON_ADJACENT_OBSERVATION_INTO_AN_AUDITABLE_QEDIMAH_PATH_AND_MANIFEST_ONLY_A_SEPARATELY_PROVEN_TRAVERSAL',
    execution_id:'EXEC-ZERA-PATH-001',
    authorization_token:'YEHI-ZERA-PATH-001-20260823'
  });
  const PLENITUDE_CONTRACT=Object.freeze({
    sequence_id:'SEQ-ZERA-CONSTITUTIVE-ADMISSION-001',version:'1.0.0',status:'AUTHORIZED',
    problem_id:'PROBLEM-ZERA-004',
    problem:'Le GPS brut entre encore comme destination de calcul avant que l espace des mouvements légitimes ait été constitué depuis la dernière Zera gouvernée.',
    law_id:'LAW-ZERA-PLENITUDE-001',
    law:'Un espace rempli depuis sa source par ses états légitimes ne combat pas l état destructeur : il ne lui fournit aucun lieu de manifestation.',
    hoq_id:'HOQ-ZERA-CONSTITUTIVE-ADMISSION-001',
    states:['LAST_GOVERNED_ZERA_LOADED','QEDEM_ADMISSIBLE_SPACE_OPENED','OBSERVATION_RECEIVED_AS_WITNESS','ADMISSIBLE_PATH_SELECTED','NO_ADMISSIBLE_MANIFESTATION','ADMISSIBLE_PATH_VALIDATED','PRESENCE_MANIFESTED'],
    preconditions:['LAST_GOVERNED_ZERA_AVAILABLE','QEDIMAH_GRAPH_PREEXISTS_OBSERVATION','RAW_GPS_NEVER_HAS_GOVERNANCE_AUTHORITY'],
    transitions:['LAST_GOVERNED_ZERA_LOADED→QEDEM_ADMISSIBLE_SPACE_OPENED','QEDEM_ADMISSIBLE_SPACE_OPENED→OBSERVATION_RECEIVED_AS_WITNESS','OBSERVATION_RECEIVED_AS_WITNESS→ADMISSIBLE_PATH_SELECTED','OBSERVATION_RECEIVED_AS_WITNESS→NO_ADMISSIBLE_MANIFESTATION','ADMISSIBLE_PATH_SELECTED→ADMISSIBLE_PATH_VALIDATED','ADMISSIBLE_PATH_VALIDATED→PRESENCE_MANIFESTED'],
    forbidden_transitions:['RAW_GPS_CELL→GOVERNED_DESTINATION','OBSERVATION→CREATE_ZERA','REJECTED_OBSERVATION→NEW_ORIGIN'],
    modules:{'MOD-247':'VALID_SPACE_BEFORE_OBSERVATION_STRUCTURED','MOD-086':'PLENITUDE_LINEAGE_REGISTERED','MOD-025':'AUTHORIZATION_TOKEN_ISSUED','MOD-207a':'QEDIMAH_ADMISSIBLE_SPACE_LOADED','MOD-031':'CONSTITUTIVE_ADMISSION_EXECUTION','MOD-207b':'ADMIT_VALID_PATH_OR_PRESERVE_FULL_ORIGIN'},
    functionality_expected:'OPEN_VALID_QEDIMAH_MOVEMENT_SPACE_BEFORE_USING_GPS_AS_A_CONTRIBUTIVE_WITNESS',
    execution_id:'EXEC-ZERA-CONSTITUTIVE-ADMISSION-001',
    authorization_token:'YEHI-ZERA-CONSTITUTIVE-ADMISSION-001-20260823'
  });
  const STATE_DATA_CONTRACT=Object.freeze({
    sequence_id:'SEQ-ZERA-DATA-CONTRACT-001',version:'1.0.0',status:'AUTHORIZED',
    problem_id:'PROBLEM-ZERA-006',
    problem:'Les moteurs territoriaux échangent des objets implicites qui confondent encore observation, estimation, preuve, chemin et position gouvernée.',
    law_id:'LAW-ZERA-STATE-ESTIMATION-001',
    law:'Une observation incertaine modifie le soutien des états territoriaux préexistants sans jamais devenir directement une position gouvernée.',
    hoq_id:'HOQ-ZERA-DATA-CONTRACT-001',
    states:['NORMALIZED_OBSERVATION','TERRITORIAL_OBSERVATION_WINDOW','ZERA_BELIEF_SET','PATH_HYPOTHESIS','EVIDENCE_BUNDLE','GOVERNED_PRESENCE_STATE'],
    preconditions:['SEVEN_DECIMAL_INPUT_PRESERVED','QEDIMAH_PREEXISTS_OBSERVATION','OBJECT_TYPE_AND_VERSION_DECLARED','PROVENANCE_PRESERVED'],
    transitions:['NORMALIZED_OBSERVATION→TERRITORIAL_OBSERVATION_WINDOW','TERRITORIAL_OBSERVATION_WINDOW→ZERA_BELIEF_SET','ZERA_BELIEF_SET→PATH_HYPOTHESIS','PATH_HYPOTHESIS→EVIDENCE_BUNDLE','EVIDENCE_BUNDLE→GOVERNED_PRESENCE_STATE'],
    forbidden_transitions:['NORMALIZED_OBSERVATION→GOVERNED_PRESENCE_STATE','ZERA_BELIEF_SET→PRESENCE_GOVERNED_WITHOUT_EVIDENCE','HEURISTIC_SUPPORT→SURVEY_ACCURACY_CLAIM','OMEH_ALONE→GOVERNED_PRESENCE_STATE'],
    modules:{'MOD-247':'SIX_VERSIONED_DATA_OBJECTS_STRUCTURED','MOD-086':'STATE_DATA_LINEAGE_REGISTERED','MOD-025':'AUTHORIZATION_TOKEN_ISSUED','MOD-207a':'CONTRACT_CHAIN_EXPECTED_LOADED','MOD-031':'STATE_CONTRACT_COMPOSITION_EXECUTION','MOD-207b':'VALID_CONTRACT_CHAIN_EXPORTED_OR_INVALID_CHAIN_REPORTED'},
    functionality_expected:'FREEZE_VALIDATE_AND_EXPORT_THE_SIX_DATA_OBJECTS_BETWEEN_OBSERVATION_ESTIMATION_PATH_EVIDENCE_AND_GOVERNANCE_ENGINES',
    execution_id:'EXEC-ZERA-DATA-CONTRACT-001',
    authorization_token:'YEHI-ZERA-DATA-CONTRACT-001-20260823'
  });
  const STATE_ESTIMATOR_CONTRACT=Object.freeze({
    sequence_id:'SEQ-ZERA-TERRITORIAL-STATE-001',version:'1.0.0',status:'AUTHORIZED',
    problem_id:'PROBLEM-ZERA-007',
    problem:'Une observation GPS bruitée est encore réduite à une cellule candidate unique, sans mémoire explicite des possibilités territoriales ni comparaison de plusieurs chemins.',
    law_id:'LAW-ZERA-STATE-ESTIMATION-001',
    law:'Une observation incertaine modifie le soutien des états territoriaux préexistants sans jamais devenir directement une position gouvernée.',
    hoq_id:'HOQ-ZERA-BELIEF-001',
    states:['GOVERNED_ORIGIN_LOADED','DYNAMIC_QEDIMAH_WINDOW_OPENED','OBSERVATION_NORMALIZED','BELIEF_UPDATED','PATH_HYPOTHESES_GENERATED','EVIDENCE_BUNDLED','PARALLEL_STATE_ESTIMATED','GOVERNANCE_UNCHANGED'],
    preconditions:['LAST_GOVERNED_ZERA_OR_CURRENT_ANCHOR_AVAILABLE','FIXED_ZERA_REGISTRY_AVAILABLE','STATE_DATA_CONTRACT_VALID','RAW_GPS_HAS_NO_GOVERNANCE_AUTHORITY'],
    transitions:['GOVERNED_ORIGIN_LOADED→DYNAMIC_QEDIMAH_WINDOW_OPENED','DYNAMIC_QEDIMAH_WINDOW_OPENED→OBSERVATION_NORMALIZED','OBSERVATION_NORMALIZED→BELIEF_UPDATED','BELIEF_UPDATED→PATH_HYPOTHESES_GENERATED','PATH_HYPOTHESES_GENERATED→EVIDENCE_BUNDLED','EVIDENCE_BUNDLED→PARALLEL_STATE_ESTIMATED','PARALLEL_STATE_ESTIMATED→GOVERNANCE_UNCHANGED'],
    forbidden_transitions:['RAW_GPS→GOVERNED_ZERA','TOP_BELIEF→PRESENCE_MANIFESTED','OUTSIDE_QEDIMAH→PATH_HYPOTHESIS','SINGLE_HEURISTIC_SCORE→SURVEY_ACCURACY','PARALLEL_ESTIMATOR→MUTATE_EXISTING_GOVERNANCE'],
    modules:{'MOD-247':'DYNAMIC_WINDOW_BELIEF_MEMORY_AND_MULTI_PATH_CONSTRAINTS_STRUCTURED','MOD-086':'PROBLEM_ZERA_007_TO_STATE_ESTIMATOR_LINEAGE_REGISTERED','MOD-025':'AUTHORIZATION_TOKEN_ISSUED','MOD-207a':'PARALLEL_TERRITORIAL_STATE_EXPECTED','MOD-031':'TERRITORIAL_STATE_ESTIMATOR_EXECUTION','MOD-207b':'ESTIMATE_AND_EXPORT_WITHOUT_GOVERNANCE_MUTATION'},
    functionality_expected:'UPDATE_A_QEDIMAH_BOUNDED_ZERA_BELIEF_SET_GENERATE_MULTIPLE_CONTINUOUS_PATH_HYPOTHESES_AND_PRESERVE_CURRENT_GOVERNANCE_AUTHORITY',
    execution_id:'EXEC-ZERA-TERRITORIAL-STATE-001',
    authorization_token:'YEHI-ZERA-TERRITORIAL-STATE-001-20260823'
  });
  const VALIDATED_PREFIX_CONTRACT=Object.freeze({
    sequence_id:'SEQ-ZERA-VALIDATED-PREFIX-001',version:'1.0.0',status:'AUTHORIZED',
    problem_id:'PROBLEM-ZERA-008',
    problem:'Un chemin partiellement démontré est actuellement soit validé en entier, soit entièrement ramené à zéro, ce qui efface les transitions initiales effectivement prouvées.',
    law_id:'LAW-ZERA-VALIDATED-PREFIX-001',
    law:'Lorsqu un chemin complet demeure incertain, toute succession initiale et continue de transitions adjacentes suffisamment attestée peut être gouvernée sans promouvoir le suffixe restant.',
    hoq_id:'HOQ-ZERA-VALIDATED-PREFIX-001',
    states:['PATH_RECEIVED','TRANSITIONS_CONSTITUTED','WITNESSES_QUALIFIED','PREFIX_EMPTY','PREFIX_PARTIALLY_VALIDATED','COMPLETE_PATH_VALIDATED','UNRESOLVED_SUFFIX_RETAINED','LAST_VALIDATED_ZERA_UPDATED'],
    preconditions:['QEDIMAH_CONTINUOUS_PATH_AVAILABLE','LAST_GOVERNED_ZERA_AVAILABLE','TRANSITION_WITNESS_PROVENANCE_AVAILABLE','AT_LEAST_ONE_DIRECT_TRAVERSAL_WITNESS_PER_VALIDATED_TRANSITION'],
    transitions:['PATH_RECEIVED→TRANSITIONS_CONSTITUTED','TRANSITIONS_CONSTITUTED→WITNESSES_QUALIFIED','WITNESSES_QUALIFIED→PREFIX_EMPTY','WITNESSES_QUALIFIED→PREFIX_PARTIALLY_VALIDATED','WITNESSES_QUALIFIED→COMPLETE_PATH_VALIDATED','PREFIX_PARTIALLY_VALIDATED→UNRESOLVED_SUFFIX_RETAINED','PREFIX_PARTIALLY_VALIDATED→LAST_VALIDATED_ZERA_UPDATED','COMPLETE_PATH_VALIDATED→LAST_VALIDATED_ZERA_UPDATED'],
    forbidden_transitions:['NON_CONSECUTIVE_TRANSITIONS→VALIDATED_PREFIX','QEDIMAH_ONLY→TRANSITION_VALIDATED','GPS_ONLY→TRANSITION_VALIDATED','CONTRADICTED_TRANSITION→VALIDATED_PREFIX','UNRESOLVED_SUFFIX→GOVERNED_PRESENCE','LATER_TRANSITION→RETROACTIVE_PRIOR_VALIDATION'],
    modules:{'MOD-247':'TRANSITION_EVIDENCE_WITNESS_STATES_AND_PREFIX_CONSTRAINTS_STRUCTURED','MOD-086':'PROBLEM_ZERA_008_TO_VALIDATED_PREFIX_LINEAGE_REGISTERED','MOD-025':'AUTHORIZATION_TOKEN_ISSUED','MOD-207a':'MANIFEST_ONLY_CONSECUTIVE_PROVEN_PREFIX','MOD-031':'ZERA_VALIDATED_PREFIX_RESOLVER_EXECUTION','MOD-207b':'UPDATE_LAST_VALIDATED_ZERA_OR_HOLD_ORIGIN'},
    functionality_expected:'EVALUATE_EACH_ADJACENT_TRANSITION_AND_MANIFEST_ONLY_THE_LONGEST_CONSECUTIVE_PREFIX_WITH_DIRECT_TRAVERSAL_EVIDENCE',
    execution_id:'EXEC-ZERA-VALIDATED-PREFIX-001',
    authorization_token:'YEHI-ZERA-VALIDATED-PREFIX-001-20260823'
  });
  const TANO_TERRITORY_CONTRACT=Object.freeze({
    sequence_id:'SEQ-TERRITORY-TANO-V001',version:'1.0.0',status:'AUTHORIZED',
    problem_id:'PROBLEM-TERRITORY-001',
    problem:'Les moteurs savent raisonner sur des Zera, mais le territoire réel de test doit exister sous une forme versionnée avant toute observation GPS.',
    law_id:'LAW-TERRITORY-QEDEMAH-001',
    law:'Une présence ne peut être gouvernée que dans un territoire préconstitué dont les cellules, coordonnées, adjacences et provenances existent avant l observation.',
    hoq_id:'HOQ-TERRITORY-R11895-001',
    states:['UNLOADED','PADA_ROAD_LOADED','ZERA_REGISTRY_CONSTITUTED','ZERA_GRAPH_CONSTITUTED','PADA_DOMAINS_BOUND','QEDEMAH_READY','TERRITORY_READY'],
    preconditions:['PADA_ROAD_R11895_AVAILABLE','FIXED_COORDINATE_REGISTRY_AVAILABLE','ADDRESS_DOMAIN_REGISTRY_AVAILABLE','METERS_PER_ZERA_EQUALS_0_36'],
    transitions:['UNLOADED→PADA_ROAD_LOADED','PADA_ROAD_LOADED→ZERA_REGISTRY_CONSTITUTED','ZERA_REGISTRY_CONSTITUTED→ZERA_GRAPH_CONSTITUTED','ZERA_GRAPH_CONSTITUTED→PADA_DOMAINS_BOUND','PADA_DOMAINS_BOUND→QEDEMAH_READY','QEDEMAH_READY→TERRITORY_READY'],
    forbidden_transitions:['GPS_OBSERVATION→CREATE_ZERA','GPS_OBSERVATION→CREATE_PADA_DOMAIN','UNLOADED→TERRITORY_READY','COMPUTED_COORDINATE→SURVEY_VALIDATED','MISSING_ICL→INVENTED_ICL'],
    modules:{'MOD-247':'PADA_STREET_ZERA_DOMAIN_AND_PROVENANCE_CONTRACT_STRUCTURED','MOD-086':'PROBLEM_TERRITORY_001_TO_R11895_LINEAGE_REGISTERED','MOD-025':'AUTHORIZATION_TOKEN_ISSUED','MOD-207a':'PRECONSTITUTE_COMPLETE_TANO_ATCHIMON_TERRITORY','MOD-031':'TANO_ATCHIMON_TERRITORY_V001_EXECUTION','MOD-207b':'281_ZERA_14_PADA_DOMAINS_AND_GRAPH_VERIFIED'},
    functionality_expected:'CONSTITUTE_RUE_TANO_ATCHIMON_AS_A_VERSIONED_281_ZERA_TERRITORY_FROM_PADA_BEFORE_ANY_GPS_OBSERVATION',
    execution_id:'EXEC-TERRITORY-TANO-V001',
    authorization_token:'YEHI-TERRITORY-TANO-V001-20260823'
  });
  function validate(contract){
    const c=contract||CONTRACT,required=['problem_id','law_id','hoq_id','sequence_id','functionality_expected','forbidden_transitions','authorization_token'];
    const missing=required.filter(k=>!c[k]||(Array.isArray(c[k])&&!c[k].length));
    return{valid:missing.length===0,missing,status:missing.length?'ORPHAN_STRUCTURE':'HSC_CONTRACT_VALID',authorized:c.status==='AUTHORIZED'&&Boolean(c.authorization_token)};
  }
  root.ZeraHSCSequenceRegistry=Object.freeze({version:'1.6.0',contract:CONTRACT,pathContract:PATH_CONTRACT,plenitudeContract:PLENITUDE_CONTRACT,stateDataContract:STATE_DATA_CONTRACT,stateEstimatorContract:STATE_ESTIMATOR_CONTRACT,validatedPrefixContract:VALIDATED_PREFIX_CONTRACT,tanoTerritoryContract:TANO_TERRITORY_CONTRACT,validate});
})(typeof window!=='undefined'?window:globalThis);
