(function(root){
'use strict';
var VERSION='4.3.0',CAMPAIGN='ZTLS-TERRITORIAL-RESOLUTION-CAMPAIGN-01',ZERA_M=0.36;
var FLOW={
 G01:['INCONNU','CONTEXT_RESOLVED','CONTEXT_JUDGED','ANCHOR_A_SEALED','ANCHOR_B_SEALED','GROUP_READY','SYSTEM_RESULT_FROZEN','WITNESS_RECORDED','PERSISTED'],
 G02:['INCONNU','ZERA_A_SEALED','ZERA_B_SEALED','ZERA_C_SEALED','GROUP_READY','SYSTEM_RESULT_FROZEN','WITNESS_RECORDED','PERSISTED']
};
function now(){return new Date().toISOString();}
function uid(p){return p+'-'+Date.now()+'-'+Math.random().toString(16).slice(2,7).toUpperCase();}
function clone(v){return JSON.parse(JSON.stringify(v==null?null:v));}
function esc(v){return String(v==null?'—':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function idx(id){var m=String(id||'').match(/Z0*(\d+)$/);return m?Number(m[1]):null;}
function finite(v){return Number.isFinite(Number(v))?Number(v):null;}
function freeze(v){if(!v||typeof v!=='object'||Object.isFrozen(v))return v;Object.keys(v).forEach(function(k){freeze(v[k]);});return Object.freeze(v);}
function nextAllowed(group,current,next){var f=FLOW[group]||[],a=f.indexOf(current),b=f.indexOf(next);return b===a+1||(current==='PERSISTED'&&next==='SYSTEM_RESULT_FROZEN');}
function cell(o,kind){
 var a=o&&o.territorialAnchor||{},s=o&&o.territorialStateEstimation||{},g=s.governedPresenceState||{};
 if(kind==='observed')return a.zeraCell&&a.zeraCell.cellId||null;
 if(kind==='candidate')return a.zeraGpsMatch&&a.zeraGpsMatch.bestMatch&&a.zeraGpsMatch.bestMatch.zeraId||cell(o,'observed');
 if(kind==='supported')return s.zeraBeliefSet&&s.zeraBeliefSet.estimatedZeraId||null;
 return g.governedZeraId||g.zeraId||o&&o.zeraValidatedPrefix&&o.zeraValidatedPrefix.governedZeraId||null;
}
function systemResolution(raw,previous){
 var a=raw&&raw.territorialAnchor||{},road=a.road||{},zc=a.zeraCell||{},state=raw&&raw.territorialStateEstimation||{},gps=a.gpsInput||{};
 var observed=cell(raw,'observed'),candidate=cell(raw,'candidate'),supported=cell(raw,'supported'),governed=cell(raw,'governed');
 var currentS=finite(road.chainageFromPartStartM),previousS=previous&&finite(previous.systemResolution.chainageM),delta=currentS!==null&&previousS!==null?currentS-previousS:null;
 return {
  observedStreet:road.street||null,candidateStreet:road.street||null,supportedStreet:road.street||null,governedStreet:road.street||null,
  observedDomain:a.selectedAddress&&a.selectedAddress.number||null,candidateDomain:a.selectedAddress&&a.selectedAddress.number||null,supportedDomain:a.selectedAddress&&a.selectedAddress.number||null,governedDomain:a.selectedAddress&&a.selectedAddress.number||null,
  observedZera:observed,candidateZera:candidate,supportedZera:supported,governedZera:governed,
  chainageM:currentS,offsetInZeraM:finite(zc.offsetWithinCellM),remainingToBoundaryM:Number.isFinite(finite(zc.offsetWithinCellM))?ZERA_M-finite(zc.offsetWithinCellM):null,
  movementFromPreviousM:delta,direction:delta===null?'UNKNOWN':delta>0?'FORWARD':delta<0?'BACKWARD':'STABLE',
  externalObservation:{lat:gps.lat||raw&&raw.point&&raw.point.lat||null,lon:gps.lon||raw&&raw.point&&raw.point.lon||null,providerDeclaredAccuracyM:gps.accuracyM||raw&&raw.accuracy||null,sampleCount:a.observationFusion&&a.observationFusion.sampleCount||0,dispersionM:a.observationFusion&&a.observationFusion.medianSpreadM||null},
  territorialConfidence:a.confidence||null,authority:{pada:'PRIMARY_FIXED_REFERENCE',gps:'OBSERVATION_AND_PRESENCE_SENSOR'},governance:state.governedPresenceState||null
 };
}
function makeObservation(group,series,raw,previous){
 var r=systemResolution(raw,previous),obs={schema:'TerritorialTestObservation',schemaVersion:'1.0.0',campaignId:CAMPAIGN,groupId:group,seriesId:series,observationId:uid('ZTLO'),timestamp:now(),territoryVersion:'TANO-ATCHIMON-v0.1',engineVersions:{cockpit:VERSION,anchor:'0.3.0',evidence:'4.3.0'},sensorObservation:clone(raw&&raw.input||raw&&raw.point||null),localAuthorities:{pada:'PRIMARY_FIXED_REFERENCE',road:r.observedStreet,qedimah:clone(raw&&raw.qedimah),zeraRegistry:'Zera Fixed Coordinate Registry v0.1',previousGovernedPresence:previous&&previous.systemResolution.governedZera||null},systemResolution:r,evidenceBundle:clone(raw&&raw.territorialStateContracts||raw&&raw.evidenceBundle||null),systemResultFrozenAt:now(),humanWitness:null,comparison:null,persistenceStatus:'SYSTEM_RESULT_FROZEN'};
 return freeze(obs);
}
function segment(a,b){var ai=idx(a&&a.systemResolution.governedZera||a&&a.systemResolution.candidateZera),bi=idx(b&&b.systemResolution.governedZera||b&&b.systemResolution.candidateZera),d=ai!==null&&bi!==null?bi-ai:null;return {anchorA:a&&a.observationId,anchorB:b&&b.observationId,zeraA:ai,zeraB:bi,signedZeraDelta:d,zeraCount:d===null?null:Math.abs(d),distanceM:d===null?null:Math.abs(d)*ZERA_M,direction:d===null?'UNKNOWN':d>=0?'FORWARD':'BACKWARD',sameRoad:Boolean(a&&b&&a.systemResolution.governedStreet===b.systemResolution.governedStreet)};}
function comparison(obs,w){var s=obs.systemResolution,actual=finite(w.actualZera),resolved=idx(s.governedZera||s.supportedZera||s.candidateZera),estimated=finite(w.estimatedMovementCm),sysMove=finite(s.movementFromPreviousM);return {domainConvergence:w.actualDomain==null?null:String(s.governedDomain)===String(w.actualDomain),zeraConvergence:actual===null||resolved===null?null:actual===resolved,relativePositionConvergence:finite(w.relativeZeraFromA)==null?null:finite(w.relativeZeraFromA)===finite(w.systemRelativeZeraFromA),movementDetectionConvergence:w.movementObserved==null?null:Boolean(w.movementObserved)===Boolean(sysMove!==null&&Math.abs(sysMove)>0),intraZeraDistanceErrorCm:estimated===null||sysMove===null?null:Math.abs(Math.abs(sysMove*100)-estimated),boundaryConvergence:w.boundaryCrossed==null?null:Boolean(w.boundaryCrossed)===Boolean(s.governedZera&&obs.localAuthorities.previousGovernedPresence&&s.governedZera!==obs.localAuthorities.previousGovernedPresence)};}
function addWitness(obs,w){if(!obs||!obs.systemResultFrozenAt)throw new Error('SYSTEM_RESULT_NOT_FROZEN');if(obs.humanWitness)throw new Error('WITNESS_ALREADY_RECORDED');var c=clone(obs);c.humanWitness=Object.assign({submittedAfterSystemResult:true,submittedAt:now()},clone(w));c.comparison=comparison(obs,c.humanWitness);c.persistenceStatus='WITNESS_RECORDED';return freeze(c);}
var MemoryStore={items:{},put:function(v){this.items[v.observationId]=clone(v);return Promise.resolve(v);},all:function(){return Promise.resolve(Object.values(this.items));}};
var Store={db:null,open:function(){if(this.db)return Promise.resolve(this.db);if(!root.indexedDB)return Promise.resolve(null);return new Promise(function(resolve,reject){var q=root.indexedDB.open('ztls-v4.3',1);q.onupgradeneeded=function(){if(!q.result.objectStoreNames.contains('observations'))q.result.createObjectStore('observations',{keyPath:'observationId'});};q.onsuccess=function(){Store.db=q.result;resolve(Store.db);};q.onerror=function(){reject(q.error);};});},put:function(v){return this.open().then(function(db){if(!db)return MemoryStore.put(v);return new Promise(function(resolve,reject){var t=db.transaction('observations','readwrite'),q=t.objectStore('observations').put(clone(v));q.onsuccess=function(){resolve(v);};q.onerror=function(){reject(q.error);};});}).catch(function(){return MemoryStore.put(v);});},all:function(){return this.open().then(function(db){if(!db)return MemoryStore.all();return new Promise(function(resolve,reject){var q=db.transaction('observations','readonly').objectStore('observations').getAll();q.onsuccess=function(){resolve(q.result||[]);};q.onerror=function(){reject(q.error);};});});}};
var Core={version:VERSION,campaignId:CAMPAIGN,flow:FLOW,nextAllowed:nextAllowed,systemResolution:systemResolution,makeObservation:makeObservation,calculateSegment:segment,addHumanWitness:addWitness,compare:comparison};
root.ZTLS43Core=Core;if(typeof module!=='undefined'&&module.exports)module.exports=Core;if(typeof document==='undefined')return;
var state={group:null,stage:'INCONNU',seriesId:null,context:null,anchors:[],observations:[],pending:null,segment:null,busy:false};
function bridge(){return root.CockpitTrajectoryBridge;}
function history(){var b=bridge();return b&&Array.isArray(b.getHistory())?b.getHistory():[];}
function acquire(){if(state.busy)return;state.busy=true;render();var before=history().length;try{root.locateMe();}catch(e){}var started=Date.now(),timer=setInterval(function(){if(history().length>before){clearInterval(timer);try{resolve(history()[0]);}catch(e){alert(e.message);}state.busy=false;render();}else if(Date.now()-started>30000){clearInterval(timer);state.busy=false;alert('Acquisition non reçue. Les données existantes sont conservées.');render();}},500);}
function resolve(raw){var prev=state.observations[state.observations.length-1]||null,obs=makeObservation(state.group,state.seriesId,raw,prev);state.pending=obs;if(state.stage==='INCONNU'&&state.group==='G01')state.context=obs;state.stage='SYSTEM_RESULT_FROZEN';}
function advance(stage){state.stage=stage;render();}
function selectGroup(g){state={group:g,stage:'INCONNU',seriesId:uid('SER'),context:null,anchors:[],observations:[],pending:null,segment:null,busy:false};render();}
function acceptContext(ok){var actual=ok?null:prompt('Situation réelle observée (rue et domaine)',''),note=prompt('Note terrain (facultative)','')||'',c=addWitness(state.context,{confirmed:ok,actualDomain:actual,note:note});Store.put(c).then(function(){state.context=c;state.pending=null;state.stage='CONTEXT_JUDGED';render();});}
function mark(label){if(!state.pending)return;var anchor=state.pending;state.anchors.push(anchor);Store.put(anchor);state.pending=null;if(state.group==='G01'){if(label==='A')advance('ANCHOR_A_SEALED');else{state.segment=segment(state.anchors[0],state.anchors[1]);advance('GROUP_READY');}}else{if(label==='A')advance('ZERA_A_SEALED');if(label==='B')advance('ZERA_B_SEALED');if(label==='C'){var ids=state.anchors.map(function(o){return idx(o.systemResolution.governedZera||o.systemResolution.candidateZera);});if(ids.some(function(v){return v===null;})||Math.abs(ids[1]-ids[0])!==1||Math.abs(ids[2]-ids[1])!==1){alert('Les trois Zera doivent être adjacentes et ordonnées.');return;}advance('GROUP_READY');}}}
function witness(){var p=state.pending;if(!p)return;var confirmed=confirm('Le résultat affiché est-il correct ?'),actualDomain=prompt('Domaine réel (facultatif)',''),actualZera=prompt('Zera réelle ou index connu (facultatif)',''),fromA=state.group==='G01'?prompt('Position réelle en Zera depuis A (facultatif)',''):'',beforeB=state.group==='G01'?prompt('Position réelle en Zera avant B (facultatif)',''):'',move=prompt('Déplacement réel estimé en cm (facultatif)',''),boundary=confirm('Une frontière de Zera a-t-elle réellement été franchie ?'),confidence=prompt('Confiance de l’estimation : FAIBLE, MOYENNE ou FORTE','MOYENNE')||'MOYENNE',note=prompt('Note terrain (facultative)','')||'';var w={confirmed:confirmed,actualDomain:actualDomain||null,actualZera:actualZera===''?null:Number(actualZera),relativeZeraFromA:fromA===''?null:Number(fromA),relativeZeraBeforeB:beforeB===''?null:Number(beforeB),estimatedMovementCm:move===''?null:Number(move),movementObserved:move===''?null:Number(move)>0,boundaryCrossed:boundary,estimateConfidence:confidence,note:note};var complete=addWitness(p,w),persisting=clone(complete);persisting.persistenceStatus='PERSISTING';state.pending=freeze(persisting);render();Store.put(complete).then(function(){var saved=clone(complete);saved.persistenceStatus='PERSISTED';state.observations.push(freeze(saved));state.pending=null;state.stage='PERSISTED';render();}).catch(function(){var retry=clone(complete);retry.persistenceStatus='RETRYABLE';state.pending=freeze(retry);render();});}
function download(name,data){var a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.href=url;a.download=name;a.click();setTimeout(function(){URL.revokeObjectURL(url);},1000);}
function exportEvidence(){Store.all().then(function(items){download(CAMPAIGN+'-'+now().replace(/[:.]/g,'-')+'.json',{schema:'ZT­LS_TERRITORIAL_RESOLUTION_CAMPAIGN',schemaVersion:'1.0.0',campaignId:CAMPAIGN,cockpitVersion:VERSION,exportedAt:now(),observations:items});});}
function resultCard(o){if(!o)return '';var s=o.systemResolution;return '<div class="ztls-result"><h3>RÉSOLUTION ZTLS™ · résultat gelé</h3><div class="ztls-grid"><div><small>Rue gouvernée</small><b>'+esc(s.governedStreet||s.observedStreet)+'</b></div><div><small>Domaine gouverné</small><b>'+esc(s.governedDomain||s.observedDomain)+'</b></div><div><small>Zera</small><b>'+esc(s.governedZera||s.candidateZera)+'</b></div><div><small>Offset intra Zera</small><b>'+esc(s.offsetInZeraM===null?null:(s.offsetInZeraM*100).toFixed(1)+' cm')+'</b></div><div><small>Delta territorial</small><b>'+esc(s.movementFromPreviousM===null?null:(s.movementFromPreviousM*100).toFixed(1)+' cm')+'</b></div><div><small>Qualité observation externe</small><b>'+esc(s.externalObservation.providerDeclaredAccuracyM)+' m</b></div></div><p><span class="ztls-badge">'+esc(o.persistenceStatus)+'</span></p></div>';}
function buttons(){if(!state.group)return '';var b=[];if(state.group==='G01'&&state.stage==='INCONNU')b.push(btn('acquire','ME SITUER'));if(state.group==='G01'&&state.stage==='SYSTEM_RESULT_FROZEN'&&state.context===state.pending)b.push(btn('context-ok','CONFIRMER LE CONTEXTE'),btn('context-no','NON CONFIRMER'));if(state.group==='G01'&&state.stage==='CONTEXT_JUDGED')b.push(btn('acquire','ACQUÉRIR A'));if(state.group==='G01'&&state.stage==='SYSTEM_RESULT_FROZEN'&&state.context!==state.pending&&state.anchors.length===0)b.push(btn('mark-a','MARQUER ZERA A'));if(state.group==='G01'&&state.stage==='ANCHOR_A_SEALED')b.push(btn('acquire','ACQUÉRIR B'));if(state.group==='G01'&&state.stage==='SYSTEM_RESULT_FROZEN'&&state.anchors.length===1)b.push(btn('mark-b','MARQUER ZERA B'));if(state.group==='G01'&&(state.stage==='GROUP_READY'||state.stage==='PERSISTED'))b.push(btn('acquire','ACQUÉRIR MA POSITION'));if(state.group==='G02'&&(['INCONNU','ZERA_A_SEALED','ZERA_B_SEALED'].indexOf(state.stage)>=0))b.push(btn('acquire','ACQUÉRIR ZERA '+(['INCONNU','ZERA_A_SEALED','ZERA_B_SEALED'].indexOf(state.stage)===0?'A':state.stage==='ZERA_A_SEALED'?'B':'C')));if(state.group==='G02'&&state.stage==='SYSTEM_RESULT_FROZEN'&&state.anchors.length<3)b.push(btn('mark-'+['a','b','c'][state.anchors.length],'SCELLER ZERA '+['A','B','C'][state.anchors.length]));if(state.group==='G02'&&(state.stage==='GROUP_READY'||state.stage==='PERSISTED'))b.push(btn('acquire','ACQUÉRIR APRÈS MOUVEMENT'));if(state.stage==='SYSTEM_RESULT_FROZEN'&&state.pending&&!(state.group==='G01'&&state.context===state.pending)&&!((state.group==='G01'&&state.anchors.length<2)||(state.group==='G02'&&state.anchors.length<3)))b.push(btn('witness','VALIDATION TERRAIN'));return b.join('');}
function btn(a,t){return '<button class="ztls-btn" data-z="'+a+'" '+(state.busy?'disabled':'')+'>'+t+'</button>';}
function render(){var v=document.getElementById('ztls-view');if(!v)return;if(!state.group){v.innerHTML='<div class="ztls-hero"><small>Cockpit Spatial™ v4.3</small><h2>ZT­LS™ Territorial Resolution Campaign 01</h2><p>Le territoire local résout · le capteur témoigne · l’humain vérifie.</p></div><div class="ztls-groups">'+btn('g01','GROUPE 01 · Segment territorial')+btn('g02','GROUPE 02 · Intra Zera')+btn('export','EXPORTER LES PREUVES')+'</div>';return;}var seg=state.segment?'<div class="ztls-result"><h3>SEGMENT CONSTITUÉ</h3><p>'+esc(state.segment.zeraA)+' → '+esc(state.segment.zeraB)+' · '+esc(state.segment.zeraCount)+' Zera · '+esc(state.segment.distanceM&&state.segment.distanceM.toFixed(2))+' m</p></div>':'';v.innerHTML='<div class="ztls-top"><button class="ztls-link" data-z="menu">← Menu</button><b>'+state.group+' · '+esc(state.stage)+'</b></div>'+seg+resultCard(state.pending)+'<div class="ztls-actions">'+buttons()+'</div><p class="ztls-meta">'+state.observations.length+' prise(s) durablement enregistrée(s).</p>';}
function ensure(){if(document.getElementById('ztls-shell'))return;var launch=document.createElement('button');launch.className='ztls-launch';launch.textContent='ZTLS™ Campaign v4.3';launch.onclick=function(){document.getElementById('ztls-shell').classList.add('open');render();};document.body.appendChild(launch);var shell=document.createElement('section');shell.id='ztls-shell';shell.innerHTML='<header><h1>Cockpit Spatial™ v4.3</h1><button data-z="close">Fermer</button></header><main id="ztls-view"></main>';shell.addEventListener('click',function(e){var z=e.target.closest('[data-z]');if(!z)return;var a=z.dataset.z;if(a==='close')shell.classList.remove('open');if(a==='menu')selectGroup(null);if(a==='g01')selectGroup('G01');if(a==='g02')selectGroup('G02');if(a==='export')exportEvidence();if(a==='acquire')acquire();if(a==='context-ok')acceptContext(true);if(a==='context-no')acceptContext(false);if(a==='mark-a')mark('A');if(a==='mark-b')mark('B');if(a==='mark-c')mark('C');if(a==='witness')witness();});document.body.appendChild(shell);render();}
root.ZTLS43={open:function(){ensure();document.getElementById('ztls-shell').classList.add('open');render();},state:function(){return clone(state);}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ensure);else ensure();
})(typeof window!=='undefined'?window:globalThis);
